[aoai]
endpoint = "https://hphphayw7biwq-openai.openai.azure.com/"
key = "6fb2a8db62fa4568b45b8729ed0fff7b"
deployment_name = "gpt-4o"
embedding_deployment_name = "text-embedding-ada-002"

[search]
endpoint = "https://hphphayw7biwq-search.search.windows.net"
key = "tdov9Vgtv1QNu5nX27sKvcBB4q2T3IWz2J92T6q4xLAzSeCTmE8M"
index_name = "vector-1733813179682"

[speech]
key = "2b49cca9f50944d0809ab04b65dee557"
region = "eastus"

[language]
endpoint = "https://hphphayw7biwq-lang.cognitiveservices.azure.com/"
key = "8d25672ae11244fda9e8f0346792efc6"

[api]
endpoint = "https://hphphayw7biwq-api.azurewebsites.net"

[cosmos]
endpoint = "https://hphphayw7biwq-cosmosdb.documents.azure.com:443/"
key = "67jVIHTWX3sOTCPOUy5Y7bzrP2wluv5gYEJCqwRZ9ylFbxfvfz2OfsBmZrOgWwejT9Wg7kjZom4IACDbJaLNsQ=="
database_name = "ContosoSuites"